### ISSUE TITLE
Doku im Storybook um MD / MDX Files erweitern

### ISSUE THREAD

**Issue by eoss-sh** [smartive-education/design-system-component-library-thierry-und-simon#22]

**Comment by THRY** [comment]
Ich kapier irgendwie nicht, wie man die bestehenden Docs ergänzen kann mit Hinweisen oder Kommentaren. Sieht für mich so aus, als kann man die default docs nur komplett überschreiben – das find ich aber nicht so sinnvoll @eoss-sh
