### ISSUE TITLE
toggle umbauen ohne headlessui

### ISSUE THREAD

**Issue by THRY** [smartive-education/design-system-component-library-thierry-und-simon#49]

**Comment by eoss-sh** [comment]
@THRY ich glaube, das problem wurde mit den node types behoben. da könnten wir ev. noch warten?

**Comment by THRY** [comment]
ah ok gut!

**Comment by THRY** [comment]
glaube, mit headlessui kann man die animation nicht über tailwind lösen. darum würd ich jetzt accessibility höher werten als animation und diese komponente mal so sein lassen
